export const mathematicsChaptersData = {
  "Grade 6": {
    CBSE: [
      { id: 1, screen: "G6MChapter1", title: "Knowing Our Numbers", description: "Large numbers, number names, and place value", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 2, screen: "G6MChapter2", title: "Whole Numbers", description: "Properties, addition, subtraction, multiplication, division", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G6MChapter3", title: "Playing with Numbers", description: "Factors, multiples, prime, composite numbers", difficulty: "Beginner", duration: "40 min", topics: 6, progress: 0 },
      { id: 4, screen: "G6MChapter4", title: "Basic Geometrical Ideas", description: "Point, line, line segment, ray, angle, polygon", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 5, screen: "G6MChapter5", title: "Understanding Elementary Shapes", description: "Triangles, quadrilaterals, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G6MChapter6", title: "Integers", description: "Positive and negative numbers, addition, subtraction", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G6MChapter7", title: "Fractions", description: "Like/unlike fractions, operations with fractions", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G6MChapter8", title: "Decimals", description: "Place value, operations with decimals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 9, screen: "G6MChapter9", title: "Data Handling", description: "Pictographs, bar graphs, tally marks", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 10, screen: "G6MChapter10", title: "Mensuration", description: "Perimeter, area, volume", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G6MChapter11", title: "Algebra", description: "Simple equations, expressions, patterns", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G6MChapter12", title: "Ratio and Proportion", description: "Understanding ratios and proportions", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 13, screen: "G6MChapter13", title: "Geometry", description: "Basic constructions, lines, angles", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G6MChapter14", title: "Symmetry", description: "Line symmetry, rotational symmetry", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G6MChapter15", title: "Practical Geometry", description: "Constructing triangles, quadrilaterals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
    ],
    ICSE: [
      { id: 1, screen: "G6MChapter1", title: "Knowing Our Numbers", description: "Large numbers, number names, and place value", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 2, screen: "G6MChapter2", title: "Whole Numbers", description: "Properties, addition, subtraction, multiplication, division", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G6MChapter3", title: "Playing with Numbers", description: "Factors, multiples, prime, composite numbers", difficulty: "Beginner", duration: "40 min", topics: 6, progress: 0 },
      { id: 4, screen: "G6MChapter4", title: "Basic Geometrical Ideas", description: "Point, line, line segment, ray, angle, polygon", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 5, screen: "G6MChapter5", title: "Understanding Elementary Shapes", description: "Triangles, quadrilaterals, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G6MChapter6", title: "Integers", description: "Positive and negative numbers, addition, subtraction", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G6MChapter7", title: "Fractions", description: "Like/unlike fractions, operations with fractions", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G6MChapter8", title: "Decimals", description: "Place value, operations with decimals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 9, screen: "G6MChapter9", title: "Data Handling", description: "Pictographs, bar graphs, tally marks", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 10, screen: "G6MChapter10", title: "Mensuration", description: "Perimeter, area, volume", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G6MChapter11", title: "Algebra", description: "Simple equations, expressions, patterns", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G6MChapter12", title: "Ratio and Proportion", description: "Understanding ratios and proportions", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 13, screen: "G6MChapter13", title: "Geometry", description: "Basic constructions, lines, angles", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G6MChapter14", title: "Symmetry", description: "Line symmetry, rotational symmetry", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G6MChapter15", title: "Practical Geometry", description: "Constructing triangles, quadrilaterals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
    ],
    WBSE: [
      { id: 1, screen: "G6MChapter1", title: "Knowing Our Numbers", description: "Large numbers, number names, and place value", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 2, screen: "G6MChapter2", title: "Whole Numbers", description: "Properties, addition, subtraction, multiplication, division", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G6MChapter3", title: "Playing with Numbers", description: "Factors, multiples, prime, composite numbers", difficulty: "Beginner", duration: "40 min", topics: 6, progress: 0 },
      { id: 4, screen: "G6MChapter4", title: "Basic Geometrical Ideas", description: "Point, line, line segment, ray, angle, polygon", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 5, screen: "G6MChapter5", title: "Understanding Elementary Shapes", description: "Triangles, quadrilaterals, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G6MChapter6", title: "Integers", description: "Positive and negative numbers, addition, subtraction", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G6MChapter7", title: "Fractions", description: "Like/unlike fractions, operations with fractions", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G6MChapter8", title: "Decimals", description: "Place value, operations with decimals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 9, screen: "G6MChapter9", title: "Data Handling", description: "Pictographs, bar graphs, tally marks", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 10, screen: "G6MChapter10", title: "Mensuration", description: "Perimeter, area, volume", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G6MChapter11", title: "Algebra", description: "Simple equations, expressions, patterns", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G6MChapter12", title: "Ratio and Proportion", description: "Understanding ratios and proportions", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 13, screen: "G6MChapter13", title: "Geometry", description: "Basic constructions, lines, angles", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G6MChapter14", title: "Symmetry", description: "Line symmetry, rotational symmetry", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G6MChapter15", title: "Practical Geometry", description: "Constructing triangles, quadrilaterals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
    ],
    Odisha: [
      { id: 1, screen: "G6MChapter1", title: "Knowing Our Numbers", description: "Large numbers, number names, and place value", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 2, screen: "G6MChapter2", title: "Whole Numbers", description: "Properties, addition, subtraction, multiplication, division", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G6MChapter3", title: "Playing with Numbers", description: "Factors, multiples, prime, composite numbers", difficulty: "Beginner", duration: "40 min", topics: 6, progress: 0 },
      { id: 4, screen: "G6MChapter4", title: "Basic Geometrical Ideas", description: "Point, line, line segment, ray, angle, polygon", difficulty: "Beginner", duration: "30 min", topics: 5, progress: 0 },
      { id: 5, screen: "G6MChapter5", title: "Understanding Elementary Shapes", description: "Triangles, quadrilaterals, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G6MChapter6", title: "Integers", description: "Positive and negative numbers, addition, subtraction", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G6MChapter7", title: "Fractions", description: "Like/unlike fractions, operations with fractions", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G6MChapter8", title: "Decimals", description: "Place value, operations with decimals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 9, screen: "G6MChapter9", title: "Data Handling", description: "Pictographs, bar graphs, tally marks", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 10, screen: "G6MChapter10", title: "Mensuration", description: "Perimeter, area, volume", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G6MChapter11", title: "Algebra", description: "Simple equations, expressions, patterns", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G6MChapter12", title: "Ratio and Proportion", description: "Understanding ratios and proportions", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 13, screen: "G6MChapter13", title: "Geometry", description: "Basic constructions, lines, angles", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G6MChapter14", title: "Symmetry", description: "Line symmetry, rotational symmetry", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G6MChapter15", title: "Practical Geometry", description: "Constructing triangles, quadrilaterals", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
    ]
  },

  "Grade 7": {
    CBSE: [
      { id: 1, screen: "G7MChapter1", title: "Integers", description: "Properties, operations and word problems", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 2, screen: "G7MChapter2", title: "Fractions and Decimals", description: "Advanced operations with fractions and decimals", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G7MChapter3", title: "Data Handling", description: "Bar graphs, histograms, pie charts", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G7MChapter4", title: "Simple Equations", description: "Solving linear equations", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G7MChapter5", title: "Lines and Angles", description: "Pairs of angles, triangle angles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G7MChapter6", title: "The Triangle and Its Properties", description: "Congruence and properties", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G7MChapter7", title: "Congruence of Triangles", description: "SSS, SAS, ASA, RHS rules", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G7MChapter8", title: "Comparing Quantities", description: "Percentage, profit and loss, simple interest", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G7MChapter9", title: "Rational Numbers", description: "Operations with rational numbers", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G7MChapter10", title: "Practical Geometry", description: "Constructing triangles, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G7MChapter11", title: "Perimeter and Area", description: "Advanced mensuration", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 12, screen: "G7MChapter12", title: "Algebra", description: "Linear expressions and identities", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G7MChapter13", title: "Exponents and Powers", description: "Laws of exponents", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G7MChapter14", title: "Symmetry", description: "Line symmetry and patterns", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G7MChapter15", title: "Visualising Solid Shapes", description: "3D shapes, nets, surface area", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
    ],
    ICSE: [
      { id: 1, screen: "G7MChapter1", title: "Integers", description: "Properties, operations and word problems", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 2, screen: "G7MChapter2", title: "Fractions and Decimals", description: "Advanced operations with fractions and decimals", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G7MChapter3", title: "Data Handling", description: "Bar graphs, histograms, pie charts", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G7MChapter4", title: "Simple Equations", description: "Solving linear equations", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G7MChapter5", title: "Lines and Angles", description: "Pairs of angles, triangle angles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G7MChapter6", title: "The Triangle and Its Properties", description: "Congruence and properties", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G7MChapter7", title: "Congruence of Triangles", description: "SSS, SAS, ASA, RHS rules", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G7MChapter8", title: "Comparing Quantities", description: "Percentage, profit and loss, simple interest", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G7MChapter9", title: "Rational Numbers", description: "Operations with rational numbers", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G7MChapter10", title: "Practical Geometry", description: "Constructing triangles, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G7MChapter11", title: "Perimeter and Area", description: "Advanced mensuration", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 12, screen: "G7MChapter12", title: "Algebra", description: "Linear expressions and identities", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G7MChapter13", title: "Exponents and Powers", description: "Laws of exponents", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G7MChapter14", title: "Symmetry", description: "Line symmetry and patterns", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G7MChapter15", title: "Visualising Solid Shapes", description: "3D shapes, nets, surface area", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
    ],
    WBSE: [
      { id: 1, screen: "G7MChapter1", title: "Integers", description: "Properties, operations and word problems", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 2, screen: "G7MChapter2", title: "Fractions and Decimals", description: "Advanced operations with fractions and decimals", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G7MChapter3", title: "Data Handling", description: "Bar graphs, histograms, pie charts", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G7MChapter4", title: "Simple Equations", description: "Solving linear equations", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G7MChapter5", title: "Lines and Angles", description: "Pairs of angles, triangle angles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G7MChapter6", title: "The Triangle and Its Properties", description: "Congruence and properties", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G7MChapter7", title: "Congruence of Triangles", description: "SSS, SAS, ASA, RHS rules", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G7MChapter8", title: "Comparing Quantities", description: "Percentage, profit and loss, simple interest", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G7MChapter9", title: "Rational Numbers", description: "Operations with rational numbers", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G7MChapter10", title: "Practical Geometry", description: "Constructing triangles, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G7MChapter11", title: "Perimeter and Area", description: "Advanced mensuration", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 12, screen: "G7MChapter12", title: "Algebra", description: "Linear expressions and identities", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G7MChapter13", title: "Exponents and Powers", description: "Laws of exponents", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G7MChapter14", title: "Symmetry", description: "Line symmetry and patterns", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G7MChapter15", title: "Visualising Solid Shapes", description: "3D shapes, nets, surface area", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
    ],
    Odisha: [
      { id: 1, screen: "G7MChapter1", title: "Integers", description: "Properties, operations and word problems", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 2, screen: "G7MChapter2", title: "Fractions and Decimals", description: "Advanced operations with fractions and decimals", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G7MChapter3", title: "Data Handling", description: "Bar graphs, histograms, pie charts", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G7MChapter4", title: "Simple Equations", description: "Solving linear equations", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G7MChapter5", title: "Lines and Angles", description: "Pairs of angles, triangle angles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 6, screen: "G7MChapter6", title: "The Triangle and Its Properties", description: "Congruence and properties", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G7MChapter7", title: "Congruence of Triangles", description: "SSS, SAS, ASA, RHS rules", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 8, screen: "G7MChapter8", title: "Comparing Quantities", description: "Percentage, profit and loss, simple interest", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G7MChapter9", title: "Rational Numbers", description: "Operations with rational numbers", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G7MChapter10", title: "Practical Geometry", description: "Constructing triangles, circles", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G7MChapter11", title: "Perimeter and Area", description: "Advanced mensuration", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
      { id: 12, screen: "G7MChapter12", title: "Algebra", description: "Linear expressions and identities", difficulty: "Beginner", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G7MChapter13", title: "Exponents and Powers", description: "Laws of exponents", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G7MChapter14", title: "Symmetry", description: "Line symmetry and patterns", difficulty: "Beginner", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G7MChapter15", title: "Visualising Solid Shapes", description: "3D shapes, nets, surface area", difficulty: "Beginner", duration: "40 min", topics: 5, progress: 0 },
    ]
  },

  "Grade 8": {
    CBSE: [
      { id: 1, screen: "G8MChapter1", title: "Rational Numbers", description: "Advanced operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G8MChapter2", title: "Linear Equations", description: "Solving equations in one variable", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G8MChapter3", title: "Understanding Quadrilaterals", description: "Properties and types", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G8MChapter4", title: "Practical Geometry", description: "Constructions and loci", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G8MChapter5", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G8MChapter6", title: "Algebra", description: "Identities and factorization", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G8MChapter7", title: "Exponents and Powers", description: "Laws and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 8, screen: "G8MChapter8", title: "Direct and Inverse Proportions", description: "Problem solving", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 9, screen: "G8MChapter9", title: "Factorization", description: "Common factor, identities", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G8MChapter10", title: "Geometry", description: "Lines, angles, triangles", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G8MChapter11", title: "Visualising Solid Shapes", description: "3D geometry", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G8MChapter12", title: "Data Handling", description: "Graphs and data interpretation", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G8MChapter13", title: "Squares and Square Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G8MChapter14", title: "Cubes and Cube Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G8MChapter15", title: "Playing with Numbers", description: "Problems on numbers", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ],
    ICSE: [
      { id: 1, screen: "G8MChapter1", title: "Rational Numbers", description: "Advanced operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G8MChapter2", title: "Linear Equations", description: "Solving equations in one variable", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G8MChapter3", title: "Understanding Quadrilaterals", description: "Properties and types", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G8MChapter4", title: "Practical Geometry", description: "Constructions and loci", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G8MChapter5", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G8MChapter6", title: "Algebra", description: "Identities and factorization", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G8MChapter7", title: "Exponents and Powers", description: "Laws and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 8, screen: "G8MChapter8", title: "Direct and Inverse Proportions", description: "Problem solving", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 9, screen: "G8MChapter9", title: "Factorization", description: "Common factor, identities", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G8MChapter10", title: "Geometry", description: "Lines, angles, triangles", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G8MChapter11", title: "Visualising Solid Shapes", description: "3D geometry", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G8MChapter12", title: "Data Handling", description: "Graphs and data interpretation", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G8MChapter13", title: "Squares and Square Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G8MChapter14", title: "Cubes and Cube Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G8MChapter15", title: "Playing with Numbers", description: "Problems on numbers", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ],
    WBSE: [
      { id: 1, screen: "G8MChapter1", title: "Rational Numbers", description: "Advanced operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G8MChapter2", title: "Linear Equations", description: "Solving equations in one variable", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G8MChapter3", title: "Understanding Quadrilaterals", description: "Properties and types", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G8MChapter4", title: "Practical Geometry", description: "Constructions and loci", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G8MChapter5", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G8MChapter6", title: "Algebra", description: "Identities and factorization", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G8MChapter7", title: "Exponents and Powers", description: "Laws and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 8, screen: "G8MChapter8", title: "Direct and Inverse Proportions", description: "Problem solving", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 9, screen: "G8MChapter9", title: "Factorization", description: "Common factor, identities", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G8MChapter10", title: "Geometry", description: "Lines, angles, triangles", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G8MChapter11", title: "Visualising Solid Shapes", description: "3D geometry", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G8MChapter12", title: "Data Handling", description: "Graphs and data interpretation", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G8MChapter13", title: "Squares and Square Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G8MChapter14", title: "Cubes and Cube Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G8MChapter15", title: "Playing with Numbers", description: "Problems on numbers", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ],
    Odisha: [
      { id: 1, screen: "G8MChapter1", title: "Rational Numbers", description: "Advanced operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G8MChapter2", title: "Linear Equations", description: "Solving equations in one variable", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 3, screen: "G8MChapter3", title: "Understanding Quadrilaterals", description: "Properties and types", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 4, screen: "G8MChapter4", title: "Practical Geometry", description: "Constructions and loci", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G8MChapter5", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G8MChapter6", title: "Algebra", description: "Identities and factorization", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G8MChapter7", title: "Exponents and Powers", description: "Laws and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 8, screen: "G8MChapter8", title: "Direct and Inverse Proportions", description: "Problem solving", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 9, screen: "G8MChapter9", title: "Factorization", description: "Common factor, identities", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G8MChapter10", title: "Geometry", description: "Lines, angles, triangles", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 11, screen: "G8MChapter11", title: "Visualising Solid Shapes", description: "3D geometry", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G8MChapter12", title: "Data Handling", description: "Graphs and data interpretation", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G8MChapter13", title: "Squares and Square Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 14, screen: "G8MChapter14", title: "Cubes and Cube Roots", description: "Methods and applications", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G8MChapter15", title: "Playing with Numbers", description: "Problems on numbers", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ]
  },

  "Grade 9": {
    CBSE: [
      { id: 1, screen: "G9MChapter1", title: "Number Systems", description: "Real numbers and operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G9MChapter2", title: "Polynomials", description: "Factorization, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G9MChapter3", title: "Coordinate Geometry", description: "Distance formula, midpoint", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 4, screen: "G9MChapter4", title: "Linear Equations in Two Variables", description: "Solution methods", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G9MChapter5", title: "Geometry", description: "Triangles, circles, constructions", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G9MChapter6", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G9MChapter7", title: "Statistics", description: "Data representation, mean, median", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G9MChapter8", title: "Probability", description: "Simple problems", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 9, screen: "G9MChapter9", title: "Algebra", description: "Linear equations, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G9MChapter10", title: "Introduction to Euclid's Geometry", description: "Axioms and postulates", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 11, screen: "G9MChapter11", title: "Coordinate Geometry", description: "Graph plotting", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 12, screen: "G9MChapter12", title: "Linear Inequalities", description: "Graphical solutions", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G9MChapter13", title: "Surface Areas and Volumes", description: "3D figures", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 14, screen: "G9MChapter14", title: "Probability", description: "Experiments and events", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G9MChapter15", title: "Statistics", description: "Advanced problems", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ],
    ICSE: [
      { id: 1, screen: "G9MChapter1", title: "Number Systems", description: "Real numbers and operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G9MChapter2", title: "Polynomials", description: "Factorization, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G9MChapter3", title: "Coordinate Geometry", description: "Distance formula, midpoint", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 4, screen: "G9MChapter4", title: "Linear Equations in Two Variables", description: "Solution methods", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G9MChapter5", title: "Geometry", description: "Triangles, circles, constructions", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G9MChapter6", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G9MChapter7", title: "Statistics", description: "Data representation, mean, median", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G9MChapter8", title: "Probability", description: "Simple problems", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 9, screen: "G9MChapter9", title: "Algebra", description: "Linear equations, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G9MChapter10", title: "Introduction to Euclid's Geometry", description: "Axioms and postulates", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 11, screen: "G9MChapter11", title: "Coordinate Geometry", description: "Graph plotting", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 12, screen: "G9MChapter12", title: "Linear Inequalities", description: "Graphical solutions", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G9MChapter13", title: "Surface Areas and Volumes", description: "3D figures", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 14, screen: "G9MChapter14", title: "Probability", description: "Experiments and events", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G9MChapter15", title: "Statistics", description: "Advanced problems", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ],
    WBSE: [
      { id: 1, screen: "G9MChapter1", title: "Number Systems", description: "Real numbers and operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G9MChapter2", title: "Polynomials", description: "Factorization, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G9MChapter3", title: "Coordinate Geometry", description: "Distance formula, midpoint", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 4, screen: "G9MChapter4", title: "Linear Equations in Two Variables", description: "Solution methods", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G9MChapter5", title: "Geometry", description: "Triangles, circles, constructions", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G9MChapter6", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G9MChapter7", title: "Statistics", description: "Data representation, mean, median", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G9MChapter8", title: "Probability", description: "Simple problems", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 9, screen: "G9MChapter9", title: "Algebra", description: "Linear equations, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G9MChapter10", title: "Introduction to Euclid's Geometry", description: "Axioms and postulates", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 11, screen: "G9MChapter11", title: "Coordinate Geometry", description: "Graph plotting", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 12, screen: "G9MChapter12", title: "Linear Inequalities", description: "Graphical solutions", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G9MChapter13", title: "Surface Areas and Volumes", description: "3D figures", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 14, screen: "G9MChapter14", title: "Probability", description: "Experiments and events", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G9MChapter15", title: "Statistics", description: "Advanced problems", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ],
    Odisha: [
      { id: 1, screen: "G9MChapter1", title: "Number Systems", description: "Real numbers and operations", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G9MChapter2", title: "Polynomials", description: "Factorization, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G9MChapter3", title: "Coordinate Geometry", description: "Distance formula, midpoint", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 4, screen: "G9MChapter4", title: "Linear Equations in Two Variables", description: "Solution methods", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 5, screen: "G9MChapter5", title: "Geometry", description: "Triangles, circles, constructions", difficulty: "Intermediate", duration: "40 min", topics: 5, progress: 0 },
      { id: 6, screen: "G9MChapter6", title: "Mensuration", description: "Surface area and volume", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 7, screen: "G9MChapter7", title: "Statistics", description: "Data representation, mean, median", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G9MChapter8", title: "Probability", description: "Simple problems", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 9, screen: "G9MChapter9", title: "Algebra", description: "Linear equations, identities", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 10, screen: "G9MChapter10", title: "Introduction to Euclid's Geometry", description: "Axioms and postulates", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 11, screen: "G9MChapter11", title: "Coordinate Geometry", description: "Graph plotting", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 12, screen: "G9MChapter12", title: "Linear Inequalities", description: "Graphical solutions", difficulty: "Intermediate", duration: "35 min", topics: 4, progress: 0 },
      { id: 13, screen: "G9MChapter13", title: "Surface Areas and Volumes", description: "3D figures", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
      { id: 14, screen: "G9MChapter14", title: "Probability", description: "Experiments and events", difficulty: "Intermediate", duration: "30 min", topics: 4, progress: 0 },
      { id: 15, screen: "G9MChapter15", title: "Statistics", description: "Advanced problems", difficulty: "Intermediate", duration: "35 min", topics: 5, progress: 0 },
    ]
  },

  "Grade 10": {
    CBSE: [
      { id: 1, screen: "G10MChapter1", title: "Real Numbers", description: "Euclid's division lemma, HCF, LCM", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G10MChapter2", title: "Polynomials", description: "Zeros of polynomials, factorization", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G10MChapter3", title: "Pair of Linear Equations in Two Variables", description: "Solution methods, word problems", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 4, screen: "G10MChapter4", title: "Quadratic Equations", description: "Roots, factorization, applications", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G10MChapter5", title: "Arithmetic Progressions", description: "Nth term, sum of n terms", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 6, screen: "G10MChapter6", title: "Triangles", description: "Similarity, Pythagoras theorem", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G10MChapter7", title: "Coordinate Geometry", description: "Distance formula, section formula", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G10MChapter8", title: "Introduction to Trigonometry", description: "Ratios, identities, heights and distances", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G10MChapter9", title: "Some Applications of Trigonometry", description: "Problems on heights and distances", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G10MChapter10", title: "Circles", description: "Tangent, chord, angles", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G10MChapter11", title: "Constructions", description: "Tangents, triangles, division of line segments", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G10MChapter12", title: "Areas Related to Circles", description: "Circumference, sector, segment", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G10MChapter13", title: "Surface Areas and Volumes", description: "Cuboid, cone, cylinder, sphere", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G10MChapter14", title: "Statistics", description: "Mean, median, mode", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 15, screen: "G10MChapter15", title: "Probability", description: "Events, probability of simple events", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
    ],
    ICSE: [
      { id: 1, screen: "G10MChapter1", title: "Real Numbers", description: "Euclid's division lemma, HCF, LCM", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G10MChapter2", title: "Polynomials", description: "Zeros of polynomials, factorization", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G10MChapter3", title: "Pair of Linear Equations in Two Variables", description: "Solution methods, word problems", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 4, screen: "G10MChapter4", title: "Quadratic Equations", description: "Roots, factorization, applications", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G10MChapter5", title: "Arithmetic Progressions", description: "Nth term, sum of n terms", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 6, screen: "G10MChapter6", title: "Triangles", description: "Similarity, Pythagoras theorem", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G10MChapter7", title: "Coordinate Geometry", description: "Distance formula, section formula", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G10MChapter8", title: "Introduction to Trigonometry", description: "Ratios, identities, heights and distances", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G10MChapter9", title: "Some Applications of Trigonometry", description: "Problems on heights and distances", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G10MChapter10", title: "Circles", description: "Tangent, chord, angles", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G10MChapter11", title: "Constructions", description: "Tangents, triangles, division of line segments", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G10MChapter12", title: "Areas Related to Circles", description: "Circumference, sector, segment", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G10MChapter13", title: "Surface Areas and Volumes", description: "Cuboid, cone, cylinder, sphere", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G10MChapter14", title: "Statistics", description: "Mean, median, mode", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 15, screen: "G10MChapter15", title: "Probability", description: "Events, probability of simple events", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
    ],
    WBSE: [
      { id: 1, screen: "G10MChapter1", title: "Real Numbers", description: "Euclid's division lemma, HCF, LCM", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G10MChapter2", title: "Polynomials", description: "Zeros of polynomials, factorization", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G10MChapter3", title: "Pair of Linear Equations in Two Variables", description: "Solution methods, word problems", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 4, screen: "G10MChapter4", title: "Quadratic Equations", description: "Roots, factorization, applications", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G10MChapter5", title: "Arithmetic Progressions", description: "Nth term, sum of n terms", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 6, screen: "G10MChapter6", title: "Triangles", description: "Similarity, Pythagoras theorem", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G10MChapter7", title: "Coordinate Geometry", description: "Distance formula, section formula", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G10MChapter8", title: "Introduction to Trigonometry", description: "Ratios, identities, heights and distances", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G10MChapter9", title: "Some Applications of Trigonometry", description: "Problems on heights and distances", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G10MChapter10", title: "Circles", description: "Tangent, chord, angles", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G10MChapter11", title: "Constructions", description: "Tangents, triangles, division of line segments", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G10MChapter12", title: "Areas Related to Circles", description: "Circumference, sector, segment", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G10MChapter13", title: "Surface Areas and Volumes", description: "Cuboid, cone, cylinder, sphere", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G10MChapter14", title: "Statistics", description: "Mean, median, mode", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 15, screen: "G10MChapter15", title: "Probability", description: "Events, probability of simple events", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
    ],
    Odisha: [
      { id: 1, screen: "G10MChapter1", title: "Real Numbers", description: "Euclid's division lemma, HCF, LCM", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 2, screen: "G10MChapter2", title: "Polynomials", description: "Zeros of polynomials, factorization", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 3, screen: "G10MChapter3", title: "Pair of Linear Equations in Two Variables", description: "Solution methods, word problems", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 4, screen: "G10MChapter4", title: "Quadratic Equations", description: "Roots, factorization, applications", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 5, screen: "G10MChapter5", title: "Arithmetic Progressions", description: "Nth term, sum of n terms", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 6, screen: "G10MChapter6", title: "Triangles", description: "Similarity, Pythagoras theorem", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 7, screen: "G10MChapter7", title: "Coordinate Geometry", description: "Distance formula, section formula", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 8, screen: "G10MChapter8", title: "Introduction to Trigonometry", description: "Ratios, identities, heights and distances", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 9, screen: "G10MChapter9", title: "Some Applications of Trigonometry", description: "Problems on heights and distances", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
      { id: 10, screen: "G10MChapter10", title: "Circles", description: "Tangent, chord, angles", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 11, screen: "G10MChapter11", title: "Constructions", description: "Tangents, triangles, division of line segments", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 12, screen: "G10MChapter12", title: "Areas Related to Circles", description: "Circumference, sector, segment", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 13, screen: "G10MChapter13", title: "Surface Areas and Volumes", description: "Cuboid, cone, cylinder, sphere", difficulty: "Advanced", duration: "40 min", topics: 5, progress: 0 },
      { id: 14, screen: "G10MChapter14", title: "Statistics", description: "Mean, median, mode", difficulty: "Advanced", duration: "35 min", topics: 5, progress: 0 },
      { id: 15, screen: "G10MChapter15", title: "Probability", description: "Events, probability of simple events", difficulty: "Advanced", duration: "35 min", topics: 4, progress: 0 },
    ]
  },
  "Grade 11": {
  CBSE: [
    { id: 1, screen: "G11MChapter1", title: "Sets", description: "Types of sets, operations, Venn diagrams", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 2, screen: "G11MChapter2", title: "Relations & Functions", description: "Domain, range, types of relations", difficulty: "Advanced", duration: "45 min", topics: 6, progress: 0 },
    { id: 3, screen: "G11MChapter3", title: "Trigonometric Functions", description: "Identities, principal values, graphs", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G11MChapter4", title: "Complex Numbers & Quadratic Equations", description: "Imaginary numbers, polar form", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G11MChapter5", title: "Permutations & Combinations", description: "Counting principles, arrangements", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 6, screen: "G11MChapter6", title: "Binomial Theorem", description: "Expansion & applications", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 7, screen: "G11MChapter7", title: "Sequences & Series", description: "AP, GP & sum formulas", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 8, screen: "G11MChapter8", title: "Straight Lines", description: "Slope, intercepts & normal form", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G11MChapter9", title: "Limits & Derivatives", description: "Introduction to calculus", difficulty: "Advanced", duration: "55 min", topics: 6, progress: 0 },
    { id: 10, screen: "G11MChapter10", title: "Statistics", description: "Variance & standard deviation", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 11, screen: "G11MChapter11", title: "Probability", description: "Random experiments & axioms", difficulty: "Intermediate", duration: "42 min", topics: 4, progress: 0 }
  ],

  ICSE: [
    { id: 1, screen: "G11MChapter1", title: "Sets", description: "Types of sets, operations, Venn diagrams", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 2, screen: "G11MChapter2", title: "Relations & Functions", description: "Domain, range, types of relations", difficulty: "Advanced", duration: "45 min", topics: 6, progress: 0 },
    { id: 3, screen: "G11MChapter3", title: "Trigonometric Functions", description: "Identities, principal values, graphs", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G11MChapter4", title: "Complex Numbers & Quadratic Equations", description: "Imaginary numbers, polar form", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G11MChapter5", title: "Permutations & Combinations", description: "Counting principles, arrangements", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 6, screen: "G11MChapter6", title: "Binomial Theorem", description: "Expansion & applications", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 7, screen: "G11MChapter7", title: "Sequences & Series", description: "AP, GP & sum formulas", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 8, screen: "G11MChapter8", title: "Straight Lines", description: "Slope, intercepts & normal form", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G11MChapter9", title: "Limits & Derivatives", description: "Introduction to calculus", difficulty: "Advanced", duration: "55 min", topics: 6, progress: 0 },
    { id: 10, screen: "G11MChapter10", title: "Statistics", description: "Variance & standard deviation", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 11, screen: "G11MChapter11", title: "Probability", description: "Random experiments & axioms", difficulty: "Intermediate", duration: "42 min", topics: 4, progress: 0 }
  ],
  WBSE: [
    { id: 1, screen: "G11MChapter1", title: "Sets", description: "Types of sets, operations, Venn diagrams", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 2, screen: "G11MChapter2", title: "Relations & Functions", description: "Domain, range, types of relations", difficulty: "Advanced", duration: "45 min", topics: 6, progress: 0 },
    { id: 3, screen: "G11MChapter3", title: "Trigonometric Functions", description: "Identities, principal values, graphs", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G11MChapter4", title: "Complex Numbers & Quadratic Equations", description: "Imaginary numbers, polar form", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G11MChapter5", title: "Permutations & Combinations", description: "Counting principles, arrangements", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 6, screen: "G11MChapter6", title: "Binomial Theorem", description: "Expansion & applications", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 7, screen: "G11MChapter7", title: "Sequences & Series", description: "AP, GP & sum formulas", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 8, screen: "G11MChapter8", title: "Straight Lines", description: "Slope, intercepts & normal form", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G11MChapter9", title: "Limits & Derivatives", description: "Introduction to calculus", difficulty: "Advanced", duration: "55 min", topics: 6, progress: 0 },
    { id: 10, screen: "G11MChapter10", title: "Statistics", description: "Variance & standard deviation", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 11, screen: "G11MChapter11", title: "Probability", description: "Random experiments & axioms", difficulty: "Intermediate", duration: "42 min", topics: 4, progress: 0 }
  ],
  Odisha: [
    { id: 1, screen: "G11MChapter1", title: "Sets", description: "Types of sets, operations, Venn diagrams", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 2, screen: "G11MChapter2", title: "Relations & Functions", description: "Domain, range, types of relations", difficulty: "Advanced", duration: "45 min", topics: 6, progress: 0 },
    { id: 3, screen: "G11MChapter3", title: "Trigonometric Functions", description: "Identities, principal values, graphs", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G11MChapter4", title: "Complex Numbers & Quadratic Equations", description: "Imaginary numbers, polar form", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G11MChapter5", title: "Permutations & Combinations", description: "Counting principles, arrangements", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 6, screen: "G11MChapter6", title: "Binomial Theorem", description: "Expansion & applications", difficulty: "Advanced", duration: "42 min", topics: 5, progress: 0 },
    { id: 7, screen: "G11MChapter7", title: "Sequences & Series", description: "AP, GP & sum formulas", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 8, screen: "G11MChapter8", title: "Straight Lines", description: "Slope, intercepts & normal form", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G11MChapter9", title: "Limits & Derivatives", description: "Introduction to calculus", difficulty: "Advanced", duration: "55 min", topics: 6, progress: 0 },
    { id: 10, screen: "G11MChapter10", title: "Statistics", description: "Variance & standard deviation", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 11, screen: "G11MChapter11", title: "Probability", description: "Random experiments & axioms", difficulty: "Intermediate", duration: "42 min", topics: 4, progress: 0 }
  ]
},
"Grade 12": {
  CBSE: [
    { id: 1, screen: "G12MChapter2", title: "Inverse Trigonometric Functions", description: "Properties, principal values", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 2, screen: "G12MChapter1", title: "Relations & Functions", description: "Types of relations & inverse functions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 3, screen: "G12MChapter3", title: "Matrices", description: "Matrix operations & transpose", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G12MChapter4", title: "Determinants", description: "Properties, adjoint & inverse", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G12MChapter5", title: "Continuity & Differentiability", description: "Chain rule, exponential & logarithmic", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 6, screen: "G12MChapter6", title: "Applications of Derivatives", description: "Rate of change, maxima minima", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 7, screen: "G12MChapter7", title: "Integrals", description: "Indefinite & definite integration", difficulty: "Advanced", duration: "60 min", topics: 8, progress: 0 },
    { id: 8, screen: "G12MChapter8", title: "Applications of Integrals", description: "Area under curves", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G12MChapter9", title: "Differential Equations", description: "Formation & solutions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 10, screen: "G12MChapter10", title: "Vector Algebra", description: "Dot product, cross product", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 11, screen: "G12MChapter11", title: "Three-Dimensional Geometry", description: "Direction cosines, distances", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 12, screen: "G12MChapter12", title: "Linear Programming", description: "Feasible region, optimization", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 13, screen: "G12MChapter13", title: "Probability", description: "Bayes theorem, conditional probability", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 }
  ],

  ICSE: [
    { id: 1, screen: "G12MChapter1", title: "Relations & Functions", description: "Types of relations & inverse functions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 2, screen: "G12MChapter2", title: "Inverse Trigonometric Functions", description: "Properties, principal values", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 3, screen: "G12MChapter3", title: "Matrices", description: "Matrix operations & transpose", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G12MChapter4", title: "Determinants", description: "Properties, adjoint & inverse", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G12MChapter5", title: "Continuity & Differentiability", description: "Chain rule, exponential & logarithmic", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 6, screen: "G12MChapter6", title: "Applications of Derivatives", description: "Rate of change, maxima minima", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 7, screen: "G12MChapter7", title: "Integrals", description: "Indefinite & definite integration", difficulty: "Advanced", duration: "60 min", topics: 8, progress: 0 },
    { id: 8, screen: "G12MChapter8", title: "Applications of Integrals", description: "Area under curves", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G12MChapter9", title: "Differential Equations", description: "Formation & solutions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 10, screen: "G12MChapter10", title: "Vector Algebra", description: "Dot product, cross product", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 11, screen: "G12MChapter11", title: "Three-Dimensional Geometry", description: "Direction cosines, distances", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 12, screen: "G12MChapter12", title: "Linear Programming", description: "Feasible region, optimization", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 13, screen: "G12MChapter13", title: "Probability", description: "Bayes theorem, conditional probability", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 }
  ],
  WBSE: [
     { id: 1, screen: "G12MChapter1", title: "Relations & Functions", description: "Types of relations & inverse functions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 2, screen: "G12MChapter2", title: "Inverse Trigonometric Functions", description: "Properties, principal values", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 3, screen: "G12MChapter3", title: "Matrices", description: "Matrix operations & transpose", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G12MChapter4", title: "Determinants", description: "Properties, adjoint & inverse", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G12MChapter5", title: "Continuity & Differentiability", description: "Chain rule, exponential & logarithmic", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 6, screen: "G12MChapter6", title: "Applications of Derivatives", description: "Rate of change, maxima minima", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 7, screen: "G12MChapter7", title: "Integrals", description: "Indefinite & definite integration", difficulty: "Advanced", duration: "60 min", topics: 8, progress: 0 },
    { id: 8, screen: "G12MChapter8", title: "Applications of Integrals", description: "Area under curves", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G12MChapter9", title: "Differential Equations", description: "Formation & solutions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 10, screen: "G12MChapter10", title: "Vector Algebra", description: "Dot product, cross product", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 11, screen: "G12MChapter11", title: "Three-Dimensional Geometry", description: "Direction cosines, distances", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 12, screen: "G12MChapter12", title: "Linear Programming", description: "Feasible region, optimization", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 13, screen: "G12MChapter13", title: "Probability", description: "Bayes theorem, conditional probability", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 }
  ],
  Odisha: [
     { id: 1, screen: "G12MChapter1", title: "Relations & Functions", description: "Types of relations & inverse functions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 2, screen: "G12MChapter2", title: "Inverse Trigonometric Functions", description: "Properties, principal values", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 3, screen: "G12MChapter3", title: "Matrices", description: "Matrix operations & transpose", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 4, screen: "G12MChapter4", title: "Determinants", description: "Properties, adjoint & inverse", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 5, screen: "G12MChapter5", title: "Continuity & Differentiability", description: "Chain rule, exponential & logarithmic", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 6, screen: "G12MChapter6", title: "Applications of Derivatives", description: "Rate of change, maxima minima", difficulty: "Advanced", duration: "55 min", topics: 7, progress: 0 },
    { id: 7, screen: "G12MChapter7", title: "Integrals", description: "Indefinite & definite integration", difficulty: "Advanced", duration: "60 min", topics: 8, progress: 0 },
    { id: 8, screen: "G12MChapter8", title: "Applications of Integrals", description: "Area under curves", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 },
    { id: 9, screen: "G12MChapter9", title: "Differential Equations", description: "Formation & solutions", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 10, screen: "G12MChapter10", title: "Vector Algebra", description: "Dot product, cross product", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 11, screen: "G12MChapter11", title: "Three-Dimensional Geometry", description: "Direction cosines, distances", difficulty: "Advanced", duration: "50 min", topics: 6, progress: 0 },
    { id: 12, screen: "G12MChapter12", title: "Linear Programming", description: "Feasible region, optimization", difficulty: "Intermediate", duration: "40 min", topics: 4, progress: 0 },
    { id: 13, screen: "G12MChapter13", title: "Probability", description: "Bayes theorem, conditional probability", difficulty: "Advanced", duration: "45 min", topics: 5, progress: 0 }
  ]
},


};